#!/usr/bin/env python3
"""Visualize motor trace CSV generated by RL runs.

Expected CSV columns:
step,time_s,env_id,joint,joint_vel_rad_s,joint_vel_rpm,applied_torque_nm,joint_power_w
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize motor trace CSV.")
    parser.add_argument("--csv", required=True, type=Path, help="Path to motor_trace.csv")
    parser.add_argument(
        "--env-id",
        type=int,
        default=None,
        help="Only visualize records for this env_id (default: all envs)",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory for per-joint png files (default: <csv_dir>/motor_trace_plots)",
    )
    parser.add_argument(
        "--include-foot",
        action="store_true",
        help="Include joints containing 'foot' in their names (default: excluded)",
    )
    parser.add_argument("--show", action="store_true", help="Show interactive plot window")
    return parser.parse_args()


def load_trace(csv_path: Path, env_id: int | None):
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    required_cols = {
        "time_s",
        "env_id",
        "joint",
        "joint_vel_rpm",
        "applied_torque_nm",
        "joint_power_w",
    }

    series = defaultdict(lambda: {"time": [], "vel": [], "torque": [], "power": []})

    with csv_path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise ValueError("CSV has no header")
        missing = required_cols.difference(reader.fieldnames)
        if missing:
            missing_str = ", ".join(sorted(missing))
            raise ValueError(f"CSV missing required columns: {missing_str}")

        for row in reader:
            row_env = int(row["env_id"])
            if env_id is not None and row_env != env_id:
                continue

            joint = row["joint"]
            series[joint]["time"].append(float(row["time_s"]))
            series[joint]["vel"].append(float(row["joint_vel_rpm"]))
            series[joint]["torque"].append(float(row["applied_torque_nm"]))
            series[joint]["power"].append(float(row["joint_power_w"]))

    if not series:
        if env_id is None:
            raise ValueError("No valid rows found in CSV")
        raise ValueError(f"No rows found for env_id={env_id}")

    return dict(sorted(series.items(), key=lambda item: item[0]))


def plot_joint(joint: str, values: dict[str, list[float]], title: str):
    fig, axes = plt.subplots(3, 1, figsize=(14, 9), sharex=True)
    t = values["time"]

    axes[0].plot(t, values["vel"], linewidth=1.2)
    axes[1].plot(t, values["torque"], linewidth=1.2)
    axes[2].plot(t, values["power"], linewidth=1.2)

    axes[0].set_ylabel("Joint Velocity (rpm)")
    axes[1].set_ylabel("Applied Torque (N*m)")
    axes[2].set_ylabel("Joint Power (W)")

    for ax in axes:
        ax.grid(True, alpha=0.3)

    axes[2].set_xlabel("Time (s)")
    axes[0].set_title(f"{title} - {joint}")
    fig.tight_layout()
    return fig


def main() -> None:
    args = parse_args()
    csv_path = args.csv.resolve()

    series = load_trace(csv_path, args.env_id)
    if not args.include_foot:
        series = {
            joint: values
            for joint, values in series.items()
            if "foot" not in joint.lower()
        }
        if not series:
            raise ValueError("No non-foot joints found after filtering")

    env_desc = f"env_id={args.env_id}" if args.env_id is not None else "all envs"
    title = f"Motor Trace ({env_desc}) - {csv_path.name}"

    out_dir = args.out_dir.resolve() if args.out_dir else (csv_path.parent / "motor_trace_plots").resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Found joints: {len(series)}")
    for joint, values in series.items():
        fig = plot_joint(joint, values, title)
        out_path = out_dir / f"{joint}.png"
        fig.savefig(out_path, dpi=180)
        print(f"Saved plot to: {out_path}")

        if args.show:
            plt.show()
        else:
            plt.close(fig)


if __name__ == "__main__":
    main()
